### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by mrogers23458** [Myuze/ubiquitous-happiness#2]
As a user,

I WANT a link or button to click
SO THAT I can register for a new account

**AC**
GIVEN a registration page
WHEN I choose to sign up
THEN I am prompted to create a username and password

WHEN I click on the register button
THEN my user credentials are saved and I am logged into the site

**Comment by Myuze** [comment]
This is what we would call an Epic, it's a big task/goal which actually breaks down in to smaller tasks and we should replace it with smaller tickets such as the backend and frontend tasks of creating routes and handlebars. Github doesn't really have an Epic task in its flow (i.e. Task with Sub Tasks).

**Comment by Myuze** [comment]
Closing this issue, and replacing with other broken down tasks.
