### ISSUE TITLE
[TASK][MODEL] Saving Comment Data to Post Model

### ISSUE THREAD

**Issue by ENguyen25** [Myuze/ubiquitous-happiness#23]
As a front-end developer,

I WANT to save comments in reference to a specific username
SO THAT a user can view comments to a forum

**AC**
GIVEN an individual forum post
WHEN a user opens the page
THEN they can see comments attached to a specific user in a specific forum post

**Comment by mrogers23458** [comment]
What do you want from the user to be left on the comment? i.e. username? post date?

**Comment by ENguyen25** [comment]
just username
