### ISSUE TITLE
[TASK][VIEW] Header Nav and Footer

### ISSUE THREAD

**Issue by Nmounce** [Myuze/ubiquitous-happiness#29]
As a Site Visitor,

Reference: header-footer.handlebars

I WANT to have navigation links
SO THAT I can navigate the site easily

AC
GIVEN a logo
WHEN I click on the logo
THEN I am taken to the homepage

GIVEN a navigation pane
WHEN I click on the home button
THEN I am taken to the homepage

GIVEN a navigation pane
WHEN I click on the blog button
THEN I am taken to the blog forum page

GIVEN a navigation pane, user is logged out
WHEN I click on the login button
THEN a login modal appears

GIVEN a navigation pane, user is logged out
WHEN I click on the register button
THEN I am taken to the register page

GIVEN a navigation pane, user is logged in
WHEN I click on the logout button
THEN my session is destroyed

GIVEN a footer
WHEN I click on the footer-text
THEN I am taken to the register page

**Comment by Myuze** [comment]
This ticket should be used to track View and Handlebars work, going to create a ticket for the routes needed.
